govuk_queries:
  - name: "Immigration Rules & Statements of Changes"
    q: '("Immigration Rules" OR "Statement of changes")'
    document_types: "guidance,policy_paper,consultation,publication,news_story"

  - name: "UKVI caseworker guidance"
    q: '("caseworker guidance" OR "staff guidance") (immigration OR visa OR asylum)'
    document_types: "guidance"

  - name: "Sponsor compliance"
    q: '("sponsor guidance" OR "sponsor licence" OR "sponsor license" OR "sponsorship") (workers OR Skilled Worker OR compliance)'
    document_types: "guidance,publication,news_story"

  - name: "CPIN"
    q: '("country policy and information note" OR CPIN)'
    document_types: "guidance,publication"

  - name: "Fees"
    q: '(fee OR fees) (visa OR immigration OR UKVI)'
    document_types: "guidance,publication,news_story"
